-- ════════════════════════════════════════════════════════════════════════
--  Venezia Cori — Analytics fai-da-te (privacy-friendly, niente cookie)
--  Esegui UNA VOLTA nello SQL Editor di Supabase.
--
--  Registra solo eventi anonimi e aggregabili: pageview, ricerche senza
--  risultati, condivisioni, modalità stadio. Nessun dato personale,
--  nessun identificatore del visitatore.
--
--  Per leggere i dati: SQL Editor di Supabase, ad esempio
--    select tipo, count(*) from events group by tipo;
--    select dati->>'q' as ricerca, count(*) from events
--      where tipo = 'search_miss' group by 1 order by 2 desc limit 20;
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.events (
  id         bigint generated by default as identity primary key,
  tipo       text  not null check (char_length(tipo) <= 40),
  dati       jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_events_tipo on public.events(tipo, created_at);

alter table public.events enable row level security;

-- anon può SOLO inserire (mai leggere/modificare): scrive l'evento e basta
create policy events_insert_anon on public.events
  for insert to anon
  with check (char_length(tipo) <= 40 and pg_column_size(dati) < 1024);

-- l'admin loggato legge tutto
create policy events_read_admin on public.events
  for select to authenticated
  using (true);
