-- ════════════════════════════════════════════════════════════════════════
--  Venezia Cori — Schema Supabase
--  Esegui questo file UNA VOLTA nello SQL Editor di Supabase.
--  Crea: tabelle (chants, media, votes) + sicurezza RLS + RPC voti + seed 18 cori.
-- ════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────
--  1. TABELLE
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.chants (
  id              bigint generated by default as identity primary key,
  titolo          text   not null,
  testo           text   not null,
  categoria       text   not null
                  check (categoria in ('classico','incoraggiamento','curva','sfotto','derby')),
  avversario      text,
  popolarita_base int    not null default 0,   -- seed coridastadio, immutabile
  voti            int    not null default 0,   -- contatore community (denormalizzato da votes)
  stato           text   not null default 'in_attesa'
                  check (stato in ('in_attesa','pubblicato','rifiutato')),
  created_at      timestamptz not null default now()
);

create table if not exists public.media (
  id          bigint generated by default as identity primary key,
  chant_id    bigint not null references public.chants(id) on delete cascade,
  piattaforma text   not null check (piattaforma in ('youtube','tiktok','instagram')),
  url         text   not null,
  stato       text   not null default 'in_attesa'
              check (stato in ('in_attesa','approvato','rifiutato')),
  in_evidenza boolean not null default false,  -- admin marca quali mostrare tra gli approvati
  created_at  timestamptz not null default now()
);

create table if not exists public.votes (
  id          bigint generated by default as identity primary key,
  chant_id    bigint not null references public.chants(id) on delete cascade,
  voter_token text   not null,                 -- uuid casuale dal localStorage del visitatore
  created_at  timestamptz not null default now(),
  unique (chant_id, voter_token)
);

create index if not exists idx_chants_stato on public.chants(stato);
create index if not exists idx_media_chant  on public.media(chant_id);

-- ─────────────────────────────────────────────────────────────────────────
--  2. RPC VOTI — incrementa in modo sicuro, dedup per voter_token
--     SECURITY DEFINER: gira coi permessi del proprietario, così anon non
--     scrive mai direttamente la tabella votes.
-- ─────────────────────────────────────────────────────────────────────────

create or replace function public.cast_vote(p_chant_id bigint, p_token text)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  -- vota solo su cori pubblicati
  if not exists (select 1 from public.chants where id = p_chant_id and stato = 'pubblicato') then
    raise exception 'coro non valido';
  end if;

  insert into public.votes (chant_id, voter_token)
  values (p_chant_id, p_token)
  on conflict (chant_id, voter_token) do nothing;

  select count(*) into v_count from public.votes where chant_id = p_chant_id;
  update public.chants set voti = v_count where id = p_chant_id;
  return v_count;
end;
$$;

grant execute on function public.cast_vote(bigint, text) to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────
--  2b. RPC PROPOSTA CORO — inserisce coro (in attesa) + eventuali video,
--      in modo atomico. Serve perché sotto RLS l'anon non può rileggere
--      l'id di un coro non pubblicato per agganciarci i media.
-- ─────────────────────────────────────────────────────────────────────────

create or replace function public.propose_chant(
  p_titolo     text,
  p_testo      text,
  p_categoria  text,
  p_avversario text   default null,
  p_media      jsonb  default '[]'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  m    jsonb;
begin
  if coalesce(trim(p_titolo), '') = '' or coalesce(trim(p_testo), '') = '' then
    raise exception 'titolo e testo obbligatori';
  end if;
  if p_categoria not in ('classico','incoraggiamento','curva','sfotto','derby') then
    raise exception 'categoria non valida';
  end if;

  insert into public.chants (titolo, testo, categoria, avversario, stato)
  values (trim(p_titolo), p_testo, p_categoria,
          nullif(trim(coalesce(p_avversario, '')), ''), 'in_attesa')
  returning id into v_id;

  for m in select * from jsonb_array_elements(coalesce(p_media, '[]'::jsonb))
  loop
    if (m->>'piattaforma') in ('youtube','tiktok','instagram')
       and coalesce(m->>'url', '') <> '' then
      insert into public.media (chant_id, piattaforma, url, stato)
      values (v_id, m->>'piattaforma', m->>'url', 'in_attesa');
    end if;
  end loop;
end;
$$;

grant execute on function public.propose_chant(text, text, text, text, jsonb) to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────
--  3. SICUREZZA (RLS) — l'unica parte che DEVE essere giusta
-- ─────────────────────────────────────────────────────────────────────────

alter table public.chants enable row level security;
alter table public.media  enable row level security;
alter table public.votes  enable row level security;

-- CHANTS ----------------------------------------------------------------
-- chiunque legge solo i cori pubblicati
create policy chants_read_public on public.chants
  for select to anon
  using (stato = 'pubblicato');

-- l'admin loggato legge tutto (anche le proposte in attesa)
create policy chants_read_admin on public.chants
  for select to authenticated
  using (true);

-- chiunque può proporre un coro, ma SOLO come bozza neutra (in attesa, niente voti/punteggio)
create policy chants_insert_proposal on public.chants
  for insert to anon
  with check (stato = 'in_attesa' and voti = 0 and popolarita_base = 0);

-- solo l'admin modifica/cancella (= approva, rifiuta, edita)
create policy chants_update_admin on public.chants
  for update to authenticated using (true) with check (true);
create policy chants_delete_admin on public.chants
  for delete to authenticated using (true);

-- MEDIA -----------------------------------------------------------------
-- chiunque vede solo i media approvati
create policy media_read_public on public.media
  for select to anon
  using (stato = 'approvato');

create policy media_read_admin on public.media
  for select to authenticated
  using (true);

-- chiunque può proporre un video, ma SOLO in attesa e non in evidenza
create policy media_insert_proposal on public.media
  for insert to anon
  with check (stato = 'in_attesa' and in_evidenza = false);

create policy media_update_admin on public.media
  for update to authenticated using (true) with check (true);
create policy media_delete_admin on public.media
  for delete to authenticated using (true);

-- VOTES -----------------------------------------------------------------
-- nessun accesso diretto per anon: si vota solo via RPC cast_vote().
-- l'admin può leggere per eventuali controlli.
create policy votes_read_admin on public.votes
  for select to authenticated
  using (true);

-- ─────────────────────────────────────────────────────────────────────────
--  4. SEED — i 18 cori storici (da js/chants-data.js), già pubblicati
-- ─────────────────────────────────────────────────────────────────────────

insert into public.chants (id, titolo, testo, categoria, avversario, popolarita_base, stato) values
(10496, 'L''Etna', E'Che bello e''ee quando erutta l''Etna\nscende tutta la lava\ne scompare Palermo!', 'sfotto', 'Palermo', 4815, 'pubblicato'),
(14093, 'Che Bello Uscire di Casa', E'Che bello e\nquando esco di casa\nper andare allo stadio\na vedere l''Unione!', 'incoraggiamento', null, 1664, 'pubblicato'),
(34543, 'Ci Accoltellano', E'ci accoltellano\npoi ci sassano\ne ci sciolgono dentro all''acido\nse ci fermano\nci controllano\ni cani scappano\ne noi cantiamo ancor\nforza unione alè\nsempre insieme a te\novunque giocherai\nsola non sarai mai', 'curva', null, 1635, 'pubblicato'),
(10469, 'Che Ne Sai', E'Che ne sai di come mi sento!!\nquando l''Unione scende in campo!!\ngioie immense forti emozioni!!\nsarò sempre su quei gradoni!!\nSemplice!!\nquesta passione per le due città!!\nsole e pioggia sarò sempre qua''!!\nè troppo forte il sentimento che mi porto dentro!!\nCiao Michael!!', 'classico', null, 1524, 'pubblicato'),
(14091, 'La Curva Sud Ti Ama', E'E forza unione\nla curva sud ti ama\ntutta la settimana\nio penso solo a te!\nArancio verde unico grande amore\nuna grande passione che c''è dentro di me\nOooh unione gol\nfino al novantesimo\nche fatica che ti chiedo\nforza unione facci un gol', 'curva', null, 1177, 'pubblicato'),
(10996, 'L''Unione / O Padovano', E'Eee oe oe oe oe oe oe l''Unione\nEee oe oe oe oe oe oe l''Unione\nEee oe oe oe oe oe oe l''Unione!!!\nE fino a quando potremo cantare\no padovano vai a cagare!!!!', 'derby', 'Padova', 732, 'pubblicato'),
(10909, 'Siamo i Leoni Arancioverdi', E'Siamo i leoni arancioverdi\ncome i color dei nostri cuor\ncon te ovunque giocherai\nnoi sempre al tuo fianco avrai!!!!\nAlé Alé unione Alé\nAlé Alé unione Alé\nAlé Alé unione Alé Alé Alé!!!!!!', 'classico', null, 97, 'pubblicato'),
(10854, 'La Nostra Passione', E'Perché l''unione è la nostra passione\ne arancioverde è la nostra storia\nalé alé alé alé unione\nalé alé alé alé alé alé unione', 'classico', null, 73, 'pubblicato'),
(66870, 'Armata Arancio Verde', E'dentro lo stadio ti sostengo\nfuori io vado a caricar\nsiamo l''armata arancio verde\nla Venezia Mestre ultrà\nforza unione facci un gol\nforza unione facci un gol\nforza unione forza unione facci un gol', 'curva', null, 78, 'pubblicato'),
(65942, 'Che Bello È (La Domenica)', E'Che bello è\nse la domenica la passo con te\nin ogni stadio canterò per te\nsei la mia vita sei unica\nmagica Unione\nche bello è', 'classico', null, 78, 'pubblicato'),
(66270, 'Noi Siamo il Venezia-Mestre', E'NOI SIAMO IL VENEZIA-MESTRE\nSIAMO SEMPRE ACCANTO A TE\nPER L''ITALIA GIREREMO ALÉ OH!\nALÉ ALÉ ALÉ OH! ALÉ ALÉ ALÉ OH!\nALÉ ALÉ ALÉ OH! FORZA UNIONE!', 'incoraggiamento', null, 58, 'pubblicato'),
(66269, 'Siamo l''Armata Arancioverde', E'SIAMO L''ARMATA ARANCIOVERDE\nE MAI NESSUN CI FERMERÀ\nNOI SAREMO SEMPRE QUA\nQUANDO L''UNIONE GIOCHERÀ\nFORZA UNIONE VINCI ANCORA PER GLI ULTRÀ', 'curva', null, 22, 'pubblicato'),
(68359, 'Forza Unione Alé', E'Forza Unione alé\nNon mollare mai\nLa sud ti seguirà\nOvunque giocherai\nChe si vinca o perda\nLotta più che puoi\nDietro alle tue spalle\nCi saremo noi', 'incoraggiamento', null, 20, 'pubblicato'),
(68723, 'Per Ogni Diffidato', E'Sai perché la curva vuole vincere\nper ogni diffidato che deve firmare\nper chi non può venire\nbisogna lottare', 'curva', null, 20, 'pubblicato'),
(67867, 'O Padovano Devi Vendere', E'o padovano devi vendere\nvattene vattene\no padovano devi vendere\nvattene vattene', 'derby', 'Padova', 16, 'pubblicato'),
(11034, 'Alé Alé Alé UNIONE', E'Alé Alé Alé UNIONE Alé!\nforza lotta vincerai!\nnon ti lasceremo mai!', 'incoraggiamento', null, 29, 'pubblicato'),
(65349, 'Il Veneto Siamo Noi', E'Il Veneto siamo noi!\nSiamo noi, solo noi\nI padroni del Veneto siamo noiiii!', 'sfotto', null, 41, 'pubblicato'),
(8848, 'Un Padovano in Croce', E'Un padovano in croce\ngridando ad alta voce\nchiedeva alla sua mamma\n"Di chi son figlio io?"\nSua madre gli rispose\nalzando la sottana:\n"O padovano mio\nsei un figlio di nessuno!"', 'derby', 'Padova', 1280, 'pubblicato')
on conflict (id) do nothing;

-- riallinea la sequenza identity così i prossimi id auto non collidono coi seed
select setval(pg_get_serial_sequence('public.chants','id'), (select max(id) from public.chants));

-- ─────────────────────────────────────────────────────────────────────────
--  5. MERCH — prodotti con link di affiliazione (gestiti solo dall'admin)
--     Nessun seed: la lista la riempi dal pannello admin (tab "Merch").
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.merch (
  id           bigint generated by default as identity primary key,
  titolo       text not null,
  descrizione  text,
  immagine_url text,
  prezzo       text,                       -- libero ("€24,90"): i prezzi Amazon cambiano
  link         text not null,              -- URL affiliato
  categoria    text,                       -- es. maglia, sciarpa, gadget
  attivo       boolean not null default true,
  ordine       int not null default 0,     -- ordinamento crescente in vetrina
  created_at   timestamptz not null default now()
);

create index if not exists idx_merch_attivo on public.merch(attivo);

alter table public.merch enable row level security;

-- pubblico: legge solo i prodotti attivi
create policy merch_read_public on public.merch
  for select to anon
  using (attivo = true);

-- l'admin loggato legge tutto (anche i disattivati)
create policy merch_read_admin on public.merch
  for select to authenticated
  using (true);

-- solo l'admin crea/modifica/elimina
create policy merch_insert_admin on public.merch
  for insert to authenticated with check (true);
create policy merch_update_admin on public.merch
  for update to authenticated using (true) with check (true);
create policy merch_delete_admin on public.merch
  for delete to authenticated using (true);
